# Generated by Django 5.0 on 2023-12-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow'), ('O', 'Orange'), ('P', 'Purple'), ('A', 'Gray'), ('M', 'Multi')], default='Green', max_length=1)),
                ('living', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='decor',
            field=models.ManyToManyField(to='main_app.decor'),
        ),
    ]
