# Generated by Django 5.0 on 2023-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_decor_friend_decor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='living',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
